/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;
import ooad_project.Project;
import ooad_project.Volunteer;
import ooad_project.controller;

/**
 *
 * @author Acer
 */
public class SearchProject extends javax.swing.JFrame {
       controller c;
    /**
     * Creates new form SearchProject
     */
    public SearchProject() {
        initComponents();
        c = new controller();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homebutton = new javax.swing.JButton();
        homebutton1 = new javax.swing.JButton();
        systemname = new javax.swing.JLabel();
        homebutton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        projectnametext = new javax.swing.JTextField();
        managernamebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        managernametext = new javax.swing.JTextField();
        projectnamebutton1 = new javax.swing.JButton();

        homebutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homebutton.setForeground(new java.awt.Color(51, 51, 0));
        homebutton.setText("Home");
        homebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebuttonMouseClicked(evt);
            }
        });
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        homebutton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homebutton1.setForeground(new java.awt.Color(51, 51, 0));
        homebutton1.setText("Home");
        homebutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebutton1MouseClicked(evt);
            }
        });
        homebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        systemname.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        systemname.setForeground(new java.awt.Color(0, 153, 153));
        systemname.setText("Donations Management System");

        homebutton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homebutton2.setForeground(new java.awt.Color(51, 51, 0));
        homebutton2.setText("Home");
        homebutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebutton2MouseClicked(evt);
            }
        });
        homebutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Search By Project Name");

        managernamebutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        managernamebutton.setForeground(new java.awt.Color(0, 102, 102));
        managernamebutton.setText("Search");
        managernamebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managernamebuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Search By Manager Name");

        projectnamebutton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        projectnamebutton1.setForeground(new java.awt.Color(0, 102, 102));
        projectnamebutton1.setText("Search");
        projectnamebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectnamebutton1ActionPerformed(evt);
            }
        });
        projectnamebutton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectnamebutton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(systemname)
                        .addGap(18, 18, 18)
                        .addComponent(homebutton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(projectnamebutton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(managernamebutton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(36, 36, 36)
                                        .addComponent(projectnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(managernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemname)
                    .addComponent(homebutton2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(projectnamebutton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managernametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(managernamebutton)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homebuttonMouseClicked

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        Home h = new Home();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_homebuttonActionPerformed

    private void homebutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebutton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton1MouseClicked

    private void homebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton1ActionPerformed

    private void homebutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebutton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton2MouseClicked

    private void homebutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton2ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton2ActionPerformed

    private void projectnamebutton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectnamebutton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectnamebutton1KeyPressed

    private void projectnamebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectnamebutton1ActionPerformed
        // TODO add your handling code here:
        String PN  = projectnametext.getText();
        
        if(PN.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the name of project!","Plain",JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
        int X = c.checkPName(PN);
        if(X == 1)
        {
        Project p = c.getProject(PN);
        ProjectDetails pd = new ProjectDetails(p);
        pd.setVisible(true);
        this.setVisible(false);
        }
        else
        {
        JOptionPane.showMessageDialog(this,"Project not found!","Plain",JOptionPane.PLAIN_MESSAGE);    
        }
        }
    }//GEN-LAST:event_projectnamebutton1ActionPerformed

    private void managernamebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managernamebuttonActionPerformed
        // TODO add your handling code here:
        String MN  = managernametext.getText();
        
        if(MN.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the Manager Name!","Plain",JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
        int X = c.checkMName(MN);
        if(X == 1)
        {
        Project p = c.getProjectByMN(MN);
        ProjectDetails pd = new ProjectDetails(p);
        pd.setVisible(true);
        this.setVisible(false);
        }
        else
        {
        JOptionPane.showMessageDialog(this,"Project not found!","Plain",JOptionPane.PLAIN_MESSAGE);    
        }
        }
        
    }//GEN-LAST:event_managernamebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homebutton;
    private javax.swing.JButton homebutton1;
    private javax.swing.JButton homebutton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton managernamebutton;
    private javax.swing.JTextField managernametext;
    private javax.swing.JButton projectnamebutton1;
    private javax.swing.JTextField projectnametext;
    private javax.swing.JLabel systemname;
    // End of variables declaration//GEN-END:variables
}
